### ISSUE TITLE
how to define a selector in generated component? 

### ISSUE THREAD

**Issue by secretgspot** [A-Tokyo/generator-at-angular#47]
let someComponent = {
	selector: 'fuzer',
  templateUrl: componentTpl,
  controller: SomeController,
  bindings: {}
};

trying to show it with < fuzer ></  fuzer > all to no effect.  What am I missing?

**Comment by A-Tokyo** [comment]
I know the selector works in **angular2**, 
In **Angular1**, however, I do it in the component.module.js as follows:
```
componentModule.component('fuzer', someComponent);
```
How to generate a component called fuzer ?
yo at-angular:component fuzer

**Comment by secretgspot** [comment]
good stuff, that clears it up :)
